import { AlertTriangle, ArrowLeft, Building2, CheckCircle2, ChevronRight, LayoutDashboard, Link2, LogOut, RefreshCw, Search, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { appPath } from "../lib/paths";
import { requireSupabase } from "../lib/supabase";
import { Logo } from "./Logo";

type DashboardData = {
  metrics: { users: number; onboarded_users: number; properties: number; published_properties: number; active_selections: number; new_users_7d: number };
  users: Array<{ id: string; name: string; slug: string | null; city: string | null; state: string | null; onboarding_completed: boolean; created_at: string }>;
  properties: Array<{ id: string; title: string; status: string; publication_status: string; owner: string; created_at: string }>;
  selections: Array<{ id: string; client_name: string; status: string; owner: string; created_at: string }>;
};

const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value));

export function AdminApp() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "setup" | "denied" | "error">("loading");
  const [query, setQuery] = useState("");

  const refresh = async () => {
    setState("loading");
    try {
      const { data, error } = await requireSupabase().rpc("get_admin_dashboard");
      if (error) throw error;
      setData(data as DashboardData);
      setState("ready");
    } catch (error) {
      const message = String(error).toLowerCase();
      setState(message.includes("get_admin_dashboard") || message.includes("schema cache") || message.includes("function") ? "setup" : message.includes("admin access") ? "denied" : "error");
    }
  };

  useEffect(() => { refresh(); }, []);
  const filteredUsers = useMemo(() => data?.users.filter(user => `${user.name} ${user.city ?? ""} ${user.state ?? ""}`.toLowerCase().includes(query.toLowerCase())) ?? [], [data, query]);
  if (state === "loading") return <Loading />;
  if (state !== "ready" || !data) return <AccessState state={state} />;

  const activation = data.metrics.users ? Math.round((data.metrics.onboarded_users / data.metrics.users) * 100) : 0;
  return <main className="min-h-screen bg-[#f7f6f2] text-ink">
    <aside className="fixed inset-y-0 left-0 hidden w-[248px] flex-col border-r border-line bg-white px-5 py-6 lg:flex"><a href={appPath("/")} className="px-2"><Logo className="origin-left scale-[.82]" /></a><div className="mt-12"><p className="px-3 font-mono text-[10px] uppercase tracking-[.14em] text-stone">Workspace</p><nav className="mt-3 space-y-1"><NavItem active icon={<LayoutDashboard size={17} />} label="Visão geral" /><NavItem icon={<Users size={17} />} label="Corretores" count={data.metrics.users} /><NavItem icon={<Building2 size={17} />} label="Imóveis" count={data.metrics.properties} /><NavItem icon={<Link2 size={17} />} label="Seleções" count={data.metrics.active_selections} /></nav></div><div className="mt-auto border-t border-line pt-5"><a href={appPath("/")} className="flex items-center gap-3 rounded-xl px-3 py-3 font-body text-[13px] font-medium text-ash transition hover:bg-paper hover:text-ink"><ArrowLeft size={16} />Voltar para a Vello</a><div className="mt-3 flex items-center gap-3 rounded-xl bg-paper p-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-ink text-[12px] font-semibold text-paper">V</span><div className="min-w-0"><p className="truncate font-body text-[12px] font-semibold">Administrador</p><p className="font-mono text-[9px] uppercase tracking-[.08em] text-stone">Acesso total</p></div><LogOut size={14} className="ml-auto text-stone" /></div></div></aside>
    <div className="lg:pl-[248px]"><header className="sticky top-0 z-10 border-b border-line bg-[#f7f6f2]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1280px] items-center justify-between px-5 sm:px-8"><a href={appPath("/")} className="lg:hidden"><Logo className="origin-left scale-[.76]" /></a><div className="hidden items-center gap-2 font-body text-[12px] text-stone lg:flex"><span>Vello</span><ChevronRight size={13} /><span className="text-ink">Administração</span></div><div className="ml-auto flex items-center gap-2"><span className="hidden rounded-full border border-line bg-white px-3 py-2 font-mono text-[9px] uppercase tracking-[.12em] text-stone sm:inline">Produção</span><button onClick={refresh} aria-label="Atualizar painel" className="inline-flex h-9 items-center gap-2 rounded-[10px] border border-line bg-white px-3 font-body text-[12px] font-semibold transition hover:border-ink"><RefreshCw size={14} /><span className="hidden sm:inline">Atualizar</span></button></div></div></header>
      <div className="mx-auto max-w-[1280px] px-5 py-8 sm:px-8 lg:py-11"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-stone">Visão geral</p><h1 className="mt-3 font-display text-[clamp(36px,4vw,54px)] font-semibold leading-none tracking-[-.065em]">Bom dia, administrador.</h1><p className="mt-4 max-w-[580px] font-body text-[15px] leading-relaxed text-ash">Acompanhe o crescimento da Vello e veja como os primeiros corretores estão usando o produto.</p></div><div className="flex w-full items-center gap-2 sm:w-auto"><div className="relative flex-1 sm:w-[220px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-stone" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar corretor" className="h-10 w-full rounded-[10px] border border-line bg-white pl-9 pr-3 font-body text-[12px] outline-none placeholder:text-stone focus:border-ink" /></div></div></div>
        <section className="mt-9 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users size={17} />} label="Corretores" value={data.metrics.users} detail={`+${data.metrics.new_users_7d} nos últimos 7 dias`} tone="dark" /><Metric icon={<CheckCircle2 size={17} />} label="Ativação" value={`${activation}%`} detail={`${data.metrics.onboarded_users} perfis concluídos`} progress={activation} /><Metric icon={<Building2 size={17} />} label="Imóveis publicados" value={data.metrics.published_properties} detail={`${data.metrics.properties} imóveis no total`} /><Metric icon={<Link2 size={17} />} label="Seleções ativas" value={data.metrics.active_selections} detail="Links prontos para clientes" /></section>
        <section className="mt-8 grid gap-6 xl:grid-cols-[1.08fr_.92fr]"><Panel title="Novos corretores" subtitle="Os cadastros mais recentes" action={`${filteredUsers.length} no total`}><div className="mb-2 hidden grid-cols-[1fr_auto] px-1 font-mono text-[9px] uppercase tracking-[.12em] text-stone sm:grid"><span>Perfil</span><span>Status</span></div>{filteredUsers.length ? filteredUsers.slice(0, 6).map(user => <div key={user.id} className="flex items-center justify-between gap-4 border-t border-line py-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#ece9e1] font-body text-[12px] font-semibold">{user.name.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><p className="truncate font-body text-[13px] font-semibold">{user.name}</p><p className="mt-1 truncate font-body text-[11px] text-ash">{[user.city, user.state].filter(Boolean).join(" · ") || "Localização não informada"}</p></div></div><div className="shrink-0 text-right"><span className={`inline-flex rounded-full px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.08em] ${user.onboarding_completed ? "bg-ink text-paper" : "bg-cream text-ash"}`}>{user.onboarding_completed ? "Ativo" : "Onboarding"}</span><p className="mt-1 font-mono text-[9px] text-stone">{date(user.created_at)}</p></div></div>) : <Empty text={query ? "Nenhum corretor encontrado." : "Nenhum corretor cadastrado ainda."} />}</Panel><Panel title="Últimos imóveis" subtitle="Conteúdo criado recentemente" action="Ver catálogo">{data.properties.length ? data.properties.slice(0, 5).map(property => <div key={property.id} className="flex items-center justify-between gap-4 border-t border-line py-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-[10px] bg-[#ece9e1]"><Building2 size={16} className="text-ash" /></span><div className="min-w-0"><p className="truncate font-body text-[13px] font-semibold">{property.title}</p><p className="mt-1 truncate font-body text-[11px] text-ash">por {property.owner}</p></div></div><div className="shrink-0 text-right"><span className={`inline-flex rounded-full px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.08em] ${property.publication_status === "published" ? "bg-ink text-paper" : "bg-cream text-ash"}`}>{property.publication_status === "published" ? "Publicado" : "Rascunho"}</span><p className="mt-1 font-mono text-[9px] text-stone">{date(property.created_at)}</p></div></div>) : <Empty text="Nenhum imóvel criado ainda." />}</Panel></section>
        <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr]"><Panel title="Seleções compartilhadas" subtitle="Conversas em andamento" action={`${data.metrics.active_selections} ativas`}>{data.selections.length ? <div className="grid gap-x-7 md:grid-cols-2">{data.selections.slice(0, 6).map(selection => <div key={selection.id} className="flex items-center justify-between gap-3 border-t border-line py-4"><div className="min-w-0"><p className="truncate font-body text-[13px] font-semibold">Seleção para {selection.client_name}</p><p className="mt-1 truncate font-body text-[11px] text-ash">por {selection.owner}</p></div><span className="rounded-full bg-cream px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.08em] text-ash">{selection.status === "active" ? "Ativa" : "Arquivada"}</span></div>)}</div> : <Empty text="Nenhuma seleção criada ainda." />}</Panel><section className="rounded-[18px] border border-line bg-ink p-6 text-paper sm:p-7"><div className="flex items-start justify-between gap-4"><span className="grid h-10 w-10 place-items-center rounded-[12px] bg-white/10"><AlertTriangle size={18} /></span><span className="font-mono text-[9px] uppercase tracking-[.12em] text-white/50">Próximo passo</span></div><h2 className="mt-8 font-display text-[25px] font-semibold leading-tight tracking-[-.04em]">Prepare a Vello para os primeiros usuários.</h2><p className="mt-3 max-w-[430px] font-body text-[13px] leading-relaxed text-white/65">Valide um cadastro, um imóvel publicado e um catálogo aberto no celular antes de convidar novos corretores.</p><a href={appPath("/dashboard")} className="mt-6 inline-flex h-10 items-center gap-2 rounded-[10px] bg-white px-4 font-body text-[12px] font-semibold text-ink">Abrir meu painel <ChevronRight size={14} /></a></section></section>
      </div></div>
  </main>;
}

function Loading() { return <main className="grid min-h-screen place-items-center bg-paper"><div className="text-center"><span className="mx-auto grid h-11 w-11 animate-pulse place-items-center rounded-[14px] bg-ink text-paper"><LayoutDashboard size={18} /></span><p className="mt-4 font-mono text-[10px] uppercase tracking-[.16em] text-stone">Carregando administração</p></div></main>; }
function NavItem({ icon, label, count, active = false }: { icon: ReactNode; label: string; count?: number; active?: boolean }) { return <button type="button" disabled={!active} aria-current={active ? "page" : undefined} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left font-body text-[13px] font-medium transition ${active ? "bg-ink text-paper" : "cursor-not-allowed text-ash/60"}`}>{icon}<span>{label}</span>{typeof count === "number" && <span className={`ml-auto font-mono text-[10px] ${active ? "text-white/60" : "text-stone"}`}>{count}</span>}</button>; }
function Metric({ icon, label, value, detail, progress, tone }: { icon: ReactNode; label: string; value: string | number; detail: string; progress?: number; tone?: "dark" }) { return <article className={`rounded-[16px] border p-5 ${tone === "dark" ? "border-ink bg-ink text-paper" : "border-line bg-white"}`}><span className={`grid h-9 w-9 place-items-center rounded-[10px] ${tone === "dark" ? "bg-white/10" : "bg-cream text-ink"}`}>{icon}</span><p className={`mt-5 font-mono text-[10px] uppercase tracking-[.12em] ${tone === "dark" ? "text-white/55" : "text-stone"}`}>{label}</p><p className="mt-2 font-display text-[34px] font-semibold tracking-[-.055em]">{value}</p><p className={`mt-2 font-body text-[12px] ${tone === "dark" ? "text-white/60" : "text-ash"}`}>{detail}</p>{typeof progress === "number" && <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-cream"><span className="block h-full rounded-full bg-ink" style={{ width: `${progress}%` }} /></div>}</article>; }
function Panel({ title, subtitle, action, children }: { title: string; subtitle: string; action?: string; children: ReactNode }) { return <section className="rounded-[18px] border border-line bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-[21px] font-semibold tracking-[-.04em]">{title}</h2><p className="mt-1 font-body text-[12px] text-ash">{subtitle}</p></div>{action && <span className="shrink-0 pt-1 font-mono text-[9px] uppercase tracking-[.1em] text-stone">{action}</span>}</div><div className="mt-5">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="border-t border-line py-7 text-center font-body text-[13px] text-ash">{text}</p>; }
function AccessState({ state }: { state: "loading" | "ready" | "setup" | "denied" | "error" }) { const setup = state === "setup"; const denied = state === "denied"; return <main className="grid min-h-screen place-items-center bg-paper p-5"><section className="w-full max-w-[550px] rounded-[20px] border border-line bg-white p-7 shadow-[0_24px_70px_rgba(11,11,10,.08)]"><Logo className="origin-left scale-[.86]" /><p className="mt-10 font-mono text-[10px] uppercase tracking-[.14em] text-stone">Administração</p><h1 className="mt-3 font-display text-[38px] font-semibold leading-[.94] tracking-[-.06em]">{setup ? "Ativação necessária." : denied ? "Acesso restrito." : "Não foi possível abrir o painel."}</h1><p className="mt-5 font-body text-[15px] leading-relaxed text-ash">{setup ? "O painel já está publicado, mas o banco de produção ainda precisa receber a configuração administrativa." : denied ? "Esta área só é liberada para contas administradoras da Vello." : "Tente atualizar a página. Se o problema continuar, confira a configuração administrativa do projeto."}</p>{setup && <ol className="mt-7 list-decimal space-y-2 border-y border-line py-5 pl-5 font-body text-[13px] leading-relaxed text-ash"><li>Aplique a migration administrativa no Supabase.</li><li>Defina <code className="font-mono text-[11px] text-ink">vello_role: admin</code> no app metadata da sua conta.</li><li>Saia e entre novamente na Vello.</li></ol>}<a href={appPath("/")} className="mt-8 inline-flex h-11 items-center rounded-[10px] bg-ink px-4 font-body text-[13px] font-semibold text-paper">Voltar para a Vello</a></section></main>; }
