import { ArrowRight, Bug, Mail } from "lucide-react";
import { useEffect } from "react";
import { appPath } from "../lib/paths";
import { setPageMeta } from "../lib/seo";
import { Logo } from "./Logo";

const supportEmail = import.meta.env.VITE_SUPPORT_EMAIL as string | undefined;
const supportContact = supportEmail || "vellocorretores@gmail.com";
const reportHref = `mailto:${supportContact}?subject=${encodeURIComponent("Reporte de erro · Vello")}&body=${encodeURIComponent("Descreva o que aconteceu, em qual página e quais passos fizeram o erro aparecer.\n\nPágina: " + window.location.href + "\nDispositivo/navegador: ")}`;

export function NotFoundPage() { useEffect(() => setPageMeta({ title: "Página não encontrada | Vello", robots: "noindex,follow" }), []); return <main className="grid min-h-screen place-items-center bg-paper p-5"><section className="w-full max-w-[700px]"><a href={appPath("/")}><Logo className="origin-left scale-[.9]" /></a><div className="mt-10 border border-line bg-white p-7 shadow-[0_24px_70px_rgba(18,40,58,.08)] sm:p-12"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Erro 404</p><h1 className="mt-5 max-w-[520px] font-display text-[clamp(46px,7vw,76px)] font-semibold leading-[.89] tracking-[-.075em]">Esta página não existe.</h1><p className="mt-6 max-w-[450px] font-body text-[16px] leading-relaxed text-ash">Talvez o link tenha mudado ou não esteja mais disponível. Volte para a Vello e encontre o que procura.</p><a href={appPath("/")} className="vello-primary bg-sky text-ink mt-9 inline-flex h-12 items-center gap-2 rounded-full px-5 font-body text-[14px] font-semibold">Voltar para a Vello <ArrowRight size={16} /></a></div></section></main>; }

const legalName = import.meta.env.VITE_LEGAL_NAME as string | undefined;
const legalDocument = import.meta.env.VITE_LEGAL_DOCUMENT as string | undefined;
const legalIdentity = legalName ? `${legalName}${legalDocument ? `, inscrita no CNPJ ${legalDocument}` : ""}` : "a equipe responsável pela Vello";
const updatedAt = "22 de setembro de 2026";

export function LegalPage({ kind }: { kind: "terms" | "privacy" }) { const privacy = kind === "privacy"; return <main className="min-h-screen bg-paper"><header className="border-b border-line bg-white"><div className="mx-auto flex h-[76px] max-w-[860px] items-center justify-between px-5 sm:px-8"><a href={appPath("/")}><Logo className="origin-left scale-[.84]" /></a><a href={appPath("/cadastro")} className="vello-primary bg-sky text-ink rounded-full px-4 py-3 font-body text-[13px] font-semibold">Criar conta</a></div></header><article className="mx-auto max-w-[860px] px-5 py-16 sm:px-8 md:py-24"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Vello · atualizado em {updatedAt}</p><h1 className="mt-5 font-display text-[clamp(44px,6vw,70px)] font-semibold leading-[.9] tracking-[-.07em]">{privacy ? "Política de Privacidade" : "Termos de Uso"}</h1><nav className="mt-6 flex gap-4 font-body text-sm"><a href={appPath("/termos")} className={privacy ? "text-ash underline underline-offset-4" : "font-semibold text-ink"}>Termos de Uso</a><a href={appPath("/privacidade")} className={privacy ? "font-semibold text-ink" : "text-ash underline underline-offset-4"}>Política de Privacidade</a></nav>{privacy ? <Privacy /> : <Terms />}</article></main>; }

export function SupportPage() { return <main className="grid min-h-screen place-items-center bg-paper p-5"><section className="w-full max-w-[620px] border border-line bg-white p-7 shadow-[0_24px_70px_rgba(18,40,58,.08)] sm:p-10"><Logo className="origin-left scale-[.86]" /><span className="mt-10 grid h-11 w-11 place-items-center rounded-[10px] bg-ink text-paper"><Mail size={20} /></span><h1 className="mt-5 font-display text-[42px] font-semibold leading-[.92] tracking-[-.06em]">Suporte Vello</h1><p className="mt-5 max-w-[460px] font-body text-[16px] leading-relaxed text-ash">Está com alguma dúvida ou encontrou um problema? Durante a beta, o suporte responde diretamente por e-mail.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><a href={`mailto:${supportContact}`} className="vello-primary bg-sky text-ink inline-flex h-12 items-center justify-center gap-2 rounded-full px-5 font-body text-[14px] font-semibold transition"><Mail size={16} /> Falar com suporte</a><a href={reportHref} className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-line bg-white px-5 font-body text-[14px] font-medium text-ink transition hover:border-ink"><Bug size={16} /> Reportar um erro</a></div><p className="mt-4 font-body text-[12px] leading-relaxed text-stone">Ao reportar, informe a página, o que você esperava acontecer e, se possível, os passos para reproduzir.</p><div className="mt-8 border-t border-line pt-5"><a href={appPath("/")} className="font-body text-[13px] text-ash underline underline-offset-4 hover:text-ink">Voltar para a Vello</a></div></section></main>; }

function Terms() { return <div className="mt-12 space-y-10 font-body text-[16px] leading-relaxed text-ash">
  <Section title="1. Aceitação"><p>Estes Termos regulam o uso da Vello, oferecida por {legalIdentity}. Ao criar uma conta ou usar a plataforma, você declara que leu e concorda com estes Termos e com a <a href={appPath("/privacidade")} className="text-ink underline underline-offset-4">Política de Privacidade</a>.</p></Section>
  <Section title="2. O que é a Vello"><p>A Vello é uma plataforma on-line para profissionais e empresas de estética e beleza criarem uma página de serviços, receberem agendamentos pela internet e organizarem a própria agenda. A Vello fornece a ferramenta; o atendimento é prestado exclusivamente pela profissional.</p></Section>
  <Section title="3. Conta"><p>Para usar o painel, você precisa ter pelo menos 18 anos, informar dados verdadeiros e manter a senha em sigilo. Você é responsável por tudo o que for feito na sua conta. Avise o suporte se suspeitar de uso indevido.</p></Section>
  <Section title="4. Plano, teste e cancelamento"><p>O preço vigente é o divulgado no site. Durante a fase beta, a Vello pode ser usada sem cobrança. Antes de iniciar qualquer cobrança, avisaremos com antecedência pelo e-mail cadastrado, e você poderá decidir se continua. Quando houver assinatura, o cancelamento poderá ser feito a qualquer momento, sem multa, mantendo o acesso até o fim do período já pago.</p></Section>
  <Section title="5. Seus serviços e suas clientes"><p>Você é a única responsável pelos serviços que oferece, pelos preços, pela confirmação ou recusa de horários, por cancelamentos e pela relação com suas clientes, inclusive pelo cumprimento das normas sanitárias e profissionais da sua atividade. A Vello não faz parte do contrato entre você e suas clientes.</p><p className="mt-3">Os dados que suas clientes informam ao agendar (nome, WhatsApp e observação) ficam disponíveis para você no painel. Use-os apenas para o atendimento e respeite a LGPD. Fotos de antes e depois só podem ser publicadas com autorização expressa da cliente.</p></Section>
  <Section title="6. Conteúdo e fotos"><p>Você mantém a titularidade do que publica e garante ter direito de usar os textos e as imagens enviados. Para exibir sua página, você autoriza a Vello a armazenar, redimensionar e mostrar esse conteúdo enquanto sua conta existir.</p></Section>
  <Section title="7. Uso proibido"><p>Não é permitido: publicar conteúdo ilegal, enganoso ou ofensivo; prometer resultados de procedimentos de forma enganosa; usar dados de terceiros sem base legal; criar agendamentos falsos; tentar acessar dados de outras contas ou burlar limites de segurança. A Vello pode remover conteúdo e suspender contas que violem estas regras.</p></Section>
  <Section title="8. Disponibilidade"><p>Trabalhamos para manter a plataforma estável e segura, mas podem ocorrer interrupções para manutenção ou por falhas de terceiros. Como a Vello está em evolução, recursos podem mudar. Mudanças relevantes serão comunicadas.</p></Section>
  <Section title="9. Responsabilidade"><p>Na extensão permitida pela lei, a Vello não responde por danos decorrentes dos serviços prestados pela profissional, de informações inseridas pelas usuárias, de faltas ou atrasos de clientes, nem de indisponibilidades causadas por terceiros. Nada nestes Termos afasta direitos garantidos pelo Código de Defesa do Consumidor, quando aplicável.</p></Section>
  <Section title="10. Encerramento"><p>Você pode excluir sua conta a qualquer momento em Configurações, no bloco Seus dados. A exclusão apaga sua página, serviços, fotos, horários e agendamentos, conforme a Política de Privacidade.</p></Section>
  <Section title="11. Alterações e lei aplicável"><p>Podemos atualizar estes Termos; a data no topo indica a versão vigente, e mudanças importantes serão avisadas. Estes Termos seguem a legislação brasileira. Fica eleito o foro do domicílio do usuário quando se tratar de relação de consumo.</p></Section>
  <Section title="12. Contato"><p>Dúvidas: <a href={`mailto:${supportContact}`} className="text-ink underline underline-offset-4">{supportContact}</a> ou a <a href={appPath("/suporte")} className="text-ink underline underline-offset-4">página de suporte</a>.</p></Section>
</div>; }
function Privacy() { return <div className="mt-12 space-y-10 font-body text-[16px] leading-relaxed text-ash">
  <Section title="1. Quem somos e nosso papel"><p>A Vello é oferecida por {legalIdentity}. Somos <b className="text-ink">controladora</b> dos dados das profissionais que criam conta. Para os dados das clientes que agendam pela página de uma profissional, a <b className="text-ink">controladora é a profissional</b>, e a Vello atua como <b className="text-ink">operadora</b>, tratando esses dados apenas para viabilizar o agendamento.</p></Section>
  <Section title="2. Quais dados tratamos"><ul className="list-disc space-y-2 pl-5"><li><b className="text-ink">Profissionais:</b> nome, e-mail, WhatsApp, cidade, bairro, endereço (exibido só se você permitir), foto, apresentação, serviços, preços, fotos dos serviços, horários e regras de agendamento.</li><li><b className="text-ink">Clientes que agendam:</b> nome, WhatsApp, observação opcional, serviço e horário escolhidos.</li><li><b className="text-ink">Navegação:</b> registros de acesso (endereço IP, data e hora) e, somente se você aceitar, cookies de medição do Google Analytics.</li></ul></Section>
  <Section title="3. Para que usamos e com qual base legal"><ul className="list-disc space-y-2 pl-5"><li>Criar e manter sua conta, publicar sua página e registrar agendamentos: <b className="text-ink">execução de contrato</b> (art. 7º, V, da LGPD).</li><li>Segurança, prevenção de fraude e de agendamentos falsos, suporte e melhoria do produto: <b className="text-ink">legítimo interesse</b> (art. 7º, IX).</li><li>Medição de uso com Google Analytics: <b className="text-ink">consentimento</b> (art. 7º, I), que você pode recusar ou retirar.</li><li>Guarda de registros de acesso por 6 meses: <b className="text-ink">obrigação legal</b> (Marco Civil da Internet, art. 15).</li></ul></Section>
  <Section title="4. Dados sensíveis"><p>A Vello não pede dados de saúde. Recomendamos que clientes não informem condições de saúde no campo de observação e que profissionais tratem esse tipo de informação diretamente, com o consentimento específico exigido pelo art. 11 da LGPD.</p></Section>
  <Section title="5. Com quem compartilhamos"><p>Não vendemos dados pessoais. Compartilhamos apenas com fornecedores necessários para operar a plataforma: <b className="text-ink">Supabase</b> (banco de dados, autenticação e armazenamento de fotos), <b className="text-ink">Vercel</b> (hospedagem do site) e <b className="text-ink">Google</b> (login com Google, se você usar, e Analytics, se você aceitar). Os dados da sua página pública (nome, cidade, serviços e o que você escolher exibir) ficam visíveis para quem acessar o seu link.</p></Section>
  <Section title="6. Transferência internacional"><p>Esses fornecedores podem armazenar dados em servidores fora do Brasil, como nos Estados Unidos. Essas transferências seguem o art. 33 da LGPD, com fornecedores que adotam cláusulas contratuais e medidas de segurança compatíveis.</p></Section>
  <Section title="7. Por quanto tempo guardamos"><p>Mantemos os dados enquanto sua conta existir. Ao excluir a conta, sua página, serviços, fotos, horários e agendamentos são apagados; cópias de segurança podem guardar dados por até 30 dias antes de serem descartadas. Registros de acesso ficam 6 meses, como exige a lei.</p></Section>
  <Section title="8. Seus direitos"><p>Você pode pedir confirmação de tratamento, acesso, correção, portabilidade, eliminação, informação sobre compartilhamento e revogação de consentimento (art. 18 da LGPD). No painel, em <b className="text-ink">Configurações, bloco Seus dados</b>, você baixa uma cópia dos seus dados e exclui sua conta sozinha. Clientes que agendaram podem falar diretamente com a profissional ou com a gente pelo contato abaixo, e encaminharemos o pedido. Você também pode reclamar à ANPD.</p></Section>
  <Section title="9. Segurança"><p>Usamos conexão criptografada (HTTPS), controle de acesso por conta no banco de dados (cada profissional só vê os próprios dados), limites contra agendamentos em massa e otimização das fotos no próprio navegador. Nenhum sistema é totalmente imune a falhas; em caso de incidente relevante, comunicaremos as pessoas afetadas e a ANPD, como prevê a lei.</p></Section>
  <Section title="10. Cookies"><p>Usamos armazenamento essencial para manter você conectada e lembrar sua escolha de cookies. Cookies de medição (Google Analytics) só são ativados se você aceitar no aviso exibido no site.</p><button type="button" onClick={resetCookieChoice} className="mt-4 h-10 rounded-full border border-line px-4 font-body text-sm font-medium text-ink transition hover:border-ink">Alterar minha escolha de cookies</button></Section>
  <Section title="11. Menores de idade"><p>A Vello é destinada a maiores de 18 anos. Não coletamos intencionalmente dados de crianças e adolescentes.</p></Section>
  <Section title="12. Encarregado e contato"><p>Para exercer seus direitos ou tirar dúvidas sobre privacidade, fale com o encarregado pelo tratamento de dados: <a href={`mailto:${supportContact}`} className="text-ink underline underline-offset-4">{supportContact}</a>.</p></Section>
  <Section title="13. Alterações"><p>Esta política pode ser atualizada. A data no topo indica a versão vigente, e mudanças relevantes serão avisadas.</p></Section>
</div>; }
function resetCookieChoice() {
  try {
    localStorage.removeItem("vello-analytics-consent");
  } catch {
    // Sem armazenamento: a escolha já não fica salva.
  }
  window.location.reload();
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="font-display text-[25px] font-semibold tracking-[-.04em] text-ink">{title}</h2><div className="mt-3">{children}</div></section>; }
