import { ArrowRight, Bug, Mail } from "lucide-react";
import { appPath } from "../lib/paths";
import { Logo } from "./Logo";

const supportEmail = import.meta.env.VITE_SUPPORT_EMAIL as string | undefined;
const supportContact = supportEmail || "vellocorretores@gmail.com";
const reportHref = `mailto:${supportContact}?subject=${encodeURIComponent("Reporte de erro · Vello")}&body=${encodeURIComponent("Descreva o que aconteceu, em qual página e quais passos fizeram o erro aparecer.\n\nPágina: " + window.location.href + "\nDispositivo/navegador: ")}`;

export function NotFoundPage() { return <main className="grid min-h-screen place-items-center bg-paper p-5"><section className="w-full max-w-[700px]"><a href={appPath("/")}><Logo className="origin-left scale-[.9]" /></a><div className="mt-10 border border-line bg-white p-7 shadow-[0_24px_70px_rgba(11,11,10,.08)] sm:p-12"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Erro 404</p><h1 className="mt-5 max-w-[520px] font-display text-[clamp(46px,7vw,76px)] font-semibold leading-[.89] tracking-[-.075em]">Esta página não existe.</h1><p className="mt-6 max-w-[450px] font-body text-[16px] leading-relaxed text-ash">Talvez o link tenha mudado ou não esteja mais disponível. Volte para a Vello e encontre o que procura.</p><a href={appPath("/")} className="mt-9 inline-flex h-12 items-center gap-2 rounded-[10px] bg-ink px-5 font-body text-[14px] font-semibold text-paper">Voltar para a Vello <ArrowRight size={16} /></a></div></section></main>; }

export function LegalPage({ kind }: { kind: "terms" | "privacy" }) { const privacy = kind === "privacy"; return <main className="min-h-screen bg-paper"><header className="border-b border-line bg-white"><div className="mx-auto flex h-[76px] max-w-[860px] items-center justify-between px-5 sm:px-8"><a href={appPath("/")}><Logo className="origin-left scale-[.84]" /></a><a href={appPath("/cadastro")} className="rounded-[10px] bg-ink px-4 py-3 font-body text-[13px] font-semibold text-paper">Criar catálogo</a></div></header><article className="mx-auto max-w-[860px] px-5 py-16 sm:px-8 md:py-24"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Vello · versão beta · 31 de agosto de 2026</p><h1 className="mt-5 font-display text-[clamp(44px,6vw,70px)] font-semibold leading-[.9] tracking-[-.07em]">{privacy ? "Política de Privacidade" : "Termos de Uso"}</h1>{privacy ? <Privacy /> : <Terms />}</article></main>; }

export function SupportPage() { return <main className="grid min-h-screen place-items-center bg-paper p-5"><section className="w-full max-w-[620px] border border-line bg-white p-7 shadow-[0_24px_70px_rgba(11,11,10,.08)] sm:p-10"><Logo className="origin-left scale-[.86]" /><span className="mt-10 grid h-11 w-11 place-items-center rounded-[10px] bg-ink text-paper"><Mail size={20} /></span><h1 className="mt-5 font-display text-[42px] font-semibold leading-[.92] tracking-[-.06em]">Suporte Vello</h1><p className="mt-5 max-w-[460px] font-body text-[16px] leading-relaxed text-ash">Está com alguma dúvida ou encontrou um problema? Durante a beta, o suporte responde diretamente por e-mail.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><a href={`mailto:${supportContact}`} className="inline-flex h-12 items-center justify-center gap-2 rounded-[10px] bg-ink px-5 font-body text-[14px] font-semibold text-paper transition hover:bg-charcoal"><Mail size={16} /> Falar com suporte</a><a href={reportHref} className="inline-flex h-12 items-center justify-center gap-2 rounded-[10px] border border-line bg-white px-5 font-body text-[14px] font-medium text-ink transition hover:border-ink"><Bug size={16} /> Reportar um erro</a></div><p className="mt-4 font-body text-[12px] leading-relaxed text-stone">Ao reportar, informe a página, o que você esperava acontecer e, se possível, os passos para reproduzir.</p><div className="mt-8 border-t border-line pt-5"><a href={appPath("/")} className="font-body text-[13px] text-ash underline underline-offset-4 hover:text-ink">Voltar para a Vello</a></div></section></main>; }

function Terms() { return <div className="mt-12 space-y-10 font-body text-[16px] leading-relaxed text-ash"><Section title="1. O que é a Vello"><p>A Vello é uma plataforma para corretores organizarem imóveis, criarem catálogos públicos e compartilharem seleções com clientes. Nesta fase, o produto é disponibilizado como beta.</p></Section><Section title="2. Sua conta e seu conteúdo"><p>Você é responsável pelas informações, imagens e imóveis publicados na sua conta. Ao utilizar a Vello, confirma que possui autorização para divulgar esse conteúdo e que as informações apresentadas são verdadeiras e atualizadas.</p></Section><Section title="3. Uso adequado"><p>Não é permitido utilizar a plataforma para publicar conteúdo ilegal, enganoso, ofensivo ou que viole direitos de terceiros. A Vello pode suspender o acesso em caso de uso indevido ou risco à segurança da plataforma.</p></Section><Section title="4. Disponibilidade"><p>Por estar em beta, a Vello pode evoluir, sofrer indisponibilidades pontuais ou ter recursos alterados. Sempre mantenha uma cópia própria das informações importantes do seu portfólio.</p></Section><Section title="5. Contato"><p>Para dúvidas sobre estes termos ou sobre a conta, utilize a página de suporte da Vello.</p></Section></div>; }
function Privacy() { return <div className="mt-12 space-y-10 font-body text-[16px] leading-relaxed text-ash"><Section title="1. Dados tratados"><p>A Vello trata dados de conta, perfil profissional, imóveis, imagens e seleções criadas por você. Dados do catálogo público, como nome profissional e canais de contato escolhidos por você, podem ser exibidos a visitantes.</p></Section><Section title="2. Finalidade"><p>Usamos esses dados para operar sua conta, publicar o catálogo, permitir o compartilhamento de seleções, prestar suporte e melhorar o produto durante a beta.</p></Section><Section title="3. Compartilhamento"><p>Os dados públicos do catálogo são exibidos somente para viabilizar a apresentação dos imóveis. Não vendemos dados pessoais. Serviços de infraestrutura e autenticação podem processar dados apenas para operar a plataforma.</p></Section><Section title="4. Controle"><p>Você pode editar dados do perfil e imóveis pelo painel. Para solicitar exportação ou exclusão da conta, entre em contato com o suporte. A solicitação será analisada conforme as obrigações legais aplicáveis.</p></Section><Section title="5. Segurança"><p>Adotamos controles de autenticação e permissões no banco de dados. Ainda assim, você deve manter sua senha protegida e revisar periodicamente os conteúdos publicados.</p></Section></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="font-display text-[25px] font-semibold tracking-[-.04em] text-ink">{title}</h2><div className="mt-3">{children}</div></section>; }
