import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, Copy, Menu, MoveRight, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { appPath } from "../lib/paths";
import { Logo } from "./Logo";
import { Container, Eyebrow, Reveal } from "./Primitives";
import { VelloProductPreview } from "./VelloProductPreview";
import { VelloHeroCatalogPreview } from "./VelloHeroCatalogPreview";

const signup = appPath("/cadastro"), demo = appPath("/jose");
const img = {
  dashboard: appPath("/landing/dashboard-real.png"), management: appPath("/landing/customizer-real.png"),
  catalog: appPath("/landing/catalog-empty-real.png"), property: appPath("/landing/property-real.png"),
  panel: appPath("/landing/dashboard-empty-real.png"), catalogDesktop: appPath("/landing/catalog-real.png"),
};
const track = (name: string, detail?: Record<string, unknown>) => window.dispatchEvent(new CustomEvent("vello:landing", { detail: { name, ...detail } }));
const nav = [["Produto", "#produto"], ["Como funciona", "#como-funciona"], ["Planos", "#planos"]];

export function VelloLanding() {
  return <div className="vello-landing min-h-screen overflow-x-hidden bg-paper text-ink"><LandingHeader /><main><Hero /><ProductCoverflow /><PainStory /><CatalogShowcase /><SelectionsShowcase /><HowItWorks /><Pricing /><Faq /><FinalCta /></main><LandingFooter /><MobileStickyCta /></div>;
}

function LandingHeader() {
  const [open, setOpen] = useState(false), [scrolled, setScrolled] = useState(false);
  useEffect(() => { const listen = () => setScrolled(window.scrollY > 20); listen(); window.addEventListener("scroll", listen, { passive: true }); return () => window.removeEventListener("scroll", listen); }, []);
  return <header className={`fixed inset-x-0 top-0 z-[60] transition-all duration-300 ${scrolled ? "border-b border-line/80 bg-paper/90 backdrop-blur-md" : "bg-paper"}`}><Container className={`flex items-center justify-between transition-all ${scrolled ? "h-[66px]" : "h-[78px]"}`}>
    <a href="#inicio" aria-label="Vello — início"><Logo className="origin-left scale-[.86]" /></a><nav className="hidden items-center gap-8 lg:flex">{nav.map(([label, target]) => <a key={target} href={target} className="font-body text-[14px] text-ash hover:text-ink">{label}</a>)}</nav>
    <div className="hidden items-center gap-5 lg:flex"><a href={appPath("/login")} className="font-body text-[14px] text-ash hover:text-ink">Entrar</a><a href={signup} onClick={() => track("header_primary_cta_click")} className="rounded-full bg-ink px-5 py-3 font-body text-[13px] font-semibold text-paper transition-transform hover:-translate-y-0.5">Criar catálogo</a></div>
    <div className="flex items-center gap-2 lg:hidden"><a href={signup} className="rounded-full bg-ink px-4 py-2.5 font-body text-[12px] font-semibold text-paper">Começar</a><button aria-label={open ? "Fechar menu" : "Abrir menu"} onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center border border-line">{open ? <X size={18} /> : <Menu size={18} />}</button></div>
  </Container><AnimatePresence>{open && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden border-t border-line bg-paper lg:hidden"><Container className="flex flex-col gap-5 py-7">{nav.map(([label, target]) => <a onClick={() => setOpen(false)} key={target} href={target} className="font-display text-[30px] font-medium tracking-[-.05em]">{label}</a>)}<a href={appPath("/login")} className="mt-2 font-body text-sm text-ash">Entrar na minha conta</a></Container></motion.div>}</AnimatePresence></header>;
}

function Hero() { return <section id="inicio" className="relative overflow-hidden bg-paper pt-[132px] md:pt-[150px]"><div aria-hidden className="pointer-events-none absolute left-[-14rem] top-0 hidden h-[65rem] w-[26rem] -rotate-45 rounded-full bg-[radial-gradient(ellipse,rgba(11,11,10,.055),transparent_65%)] lg:block" /><Container className="relative"><Reveal y={16} className="mx-auto max-w-[760px] text-center"><Eyebrow>Catálogo digital para corretores</Eyebrow><h1 className="mt-5 font-display text-[clamp(48px,5.7vw,78px)] font-medium leading-[.94] tracking-[-.07em]">Seus imóveis,<br />apresentados do jeito certo.</h1><p className="mx-auto mt-6 max-w-[620px] font-body text-[16px] leading-[1.6] text-ash md:text-[18px]">Organize seu portfólio, crie seleções para cada cliente e compartilhe tudo em um único link.</p><a id="hero-primary-cta" href={signup} onClick={() => track("hero_primary_cta_click")} className="mt-8 inline-flex items-center gap-3 rounded-full bg-ink px-7 py-4 font-body text-[14px] font-semibold text-paper hover:-translate-y-0.5">Criar meu catálogo <MoveRight size={16} /></a></Reveal></Container><motion.div initial={{ opacity: 0, y: 32 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .1 }} className="relative mx-auto -mb-36 mt-1 max-w-[1536px] sm:-mb-32 sm:mt-6 lg:-mb-40 lg:mt-10"><div className="mx-2 [perspective:1200px] sm:mx-0 sm:-mr-16 sm:translate-x-4 sm:pl-16 lg:-mr-56 lg:translate-x-5 lg:pl-56"><div className="[transform:rotateX(20deg)]"><div className="relative h-[430px] skew-x-[.36rad] overflow-hidden rounded-t-[24px] border border-ink/15 bg-paper shadow-[0_34px_86px_rgba(11,11,10,.16)] sm:h-[440px] lg:h-[610px] lg:rounded-t-[32px]"><div className="relative z-[2] w-[250%] origin-top translate-x-[-310px] scale-[.4] [backface-visibility:hidden] sm:w-[181.82%] sm:translate-x-0 sm:scale-[.55] lg:w-[172.5%] lg:scale-[.58]"><VelloHeroCatalogPreview /></div></div></div></div><div aria-hidden className="pointer-events-none absolute inset-x-0 bottom-0 z-10 h-[18%] bg-gradient-to-b from-transparent via-paper/15 to-paper" /></motion.div></section>; }

const screens = [["Painel", "Tudo no lugar.", "dashboard"], ["Imóveis", "Cadastre uma vez.", "property"], ["Catálogo", "Um link que parece seu.", "catalog"], ["Seleções", "Cada cliente vê o que importa.", "selection"], ["Compartilhar", "Pronto para enviar.", "share"]] as const;
function ProductCoverflow() {
  const [active, setActive] = useState(2), touch = useRef<number | null>(null);
  const move = (delta: number) => setActive(v => (v + delta + screens.length) % screens.length);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "ArrowLeft") move(-1); if (e.key === "ArrowRight") move(1); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  const relative = (i: number) => { let d = i - active; if (d > 2) d -= 5; if (d < -2) d += 5; return d; };
  const current = screens[active];
  return <section id="produto" className="overflow-hidden bg-paper pb-24 pt-2 md:py-36"><Container><div className="max-w-[690px]"><Eyebrow>Por dentro da Vello</Eyebrow><h2 className="mt-5 font-display text-[clamp(43px,5.4vw,76px)] font-medium leading-[.94] tracking-[-.07em]">Conheça a Vello<br />antes mesmo de criar a sua.</h2><p className="mt-6 max-w-[520px] font-body text-[16px] leading-relaxed text-ash md:text-[18px]">Deslize pelas telas e veja do painel ao catálogo que chega no cliente.</p></div></Container><div className="mx-auto mt-14 max-w-[1540px]" onTouchStart={e => { touch.current = e.touches[0].clientX; }} onTouchEnd={e => { if (touch.current === null) return; const delta = e.changedTouches[0].clientX - touch.current; if (Math.abs(delta) > 40) { move(delta > 0 ? -1 : 1); track("product_carousel_interaction"); } touch.current = null; }}><div className="relative h-[500px] overflow-hidden sm:h-[610px] md:h-[690px]" aria-roledescription="carousel" aria-label="Telas reais da Vello">{screens.map(([title, phrase, screen], i) => { const distance = relative(i), focused = distance === 0; return <motion.button key={title} aria-label={`Ver tela ${title}: ${phrase}`} aria-current={focused} onClick={() => { setActive(i); track("product_carousel_slide_view", { slide: title }); }} animate={{ x: `${distance * 50}%`, y: Math.abs(distance) * 24, scale: focused ? 1 : Math.abs(distance) === 1 ? .84 : .7, opacity: focused ? 1 : Math.abs(distance) === 1 ? .78 : .38, zIndex: 5 - Math.abs(distance) }} transition={{ type: "spring", stiffness: 220, damping: 28, mass: .8 }} className="absolute left-1/2 top-0 h-[470px] w-[248px] -translate-x-1/2 cursor-pointer overflow-hidden rounded-[31px] border-[7px] border-ink bg-paper text-left shadow-[0_24px_48px_rgba(11,11,10,.18)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 sm:h-[570px] sm:w-[300px] sm:rounded-[39px] sm:border-[8px] md:h-[640px] md:w-[336px]"><span className="absolute left-1/2 top-2 z-20 h-5 w-[40%] -translate-x-1/2 rounded-full bg-ink sm:top-3 sm:h-6" /><VelloProductPreview screen={screen} /></motion.button>; })}</div><div className="mx-auto mt-4 flex max-w-[1040px] items-end justify-between border-t border-line px-5 pt-5 sm:px-0"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-stone">{current[0]}</p><p className="mt-1 font-display text-[24px] font-medium tracking-[-.04em]">{current[1]}</p></div><div className="flex items-center gap-3"><span className="font-mono text-[11px] text-stone">0{active + 1} / 05</span><button onClick={() => move(-1)} aria-label="Tela anterior" className="grid h-11 w-11 place-items-center border border-line hover:bg-cream"><ArrowLeft size={17} /></button><button onClick={() => move(1)} aria-label="Próxima tela" className="grid h-11 w-11 place-items-center border border-line hover:bg-cream"><ArrowRight size={17} /></button></div></div></div></section>;
}

function PainStory() { return <section className="overflow-hidden bg-ink py-24 text-paper md:py-36"><Container><div className="grid gap-14 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><Reveal><Eyebrow>Quando tudo fica solto</Eyebrow><h2 className="mt-5 max-w-[520px] font-display text-[clamp(46px,5.4vw,78px)] font-medium leading-[.91] tracking-[-.075em] text-paper">Seu portfólio<br />não deveria morar<br />no rolo da câmera.</h2><p className="mt-7 max-w-[460px] font-body text-[16px] leading-relaxed text-paper/65">Fotos soltas, PDFs antigos e mensagens perdidas deixam a apresentação do seu trabalho pior do que ele é.</p></Reveal><Reveal delay={.12} className="relative min-h-[420px] sm:min-h-[560px]"><div className="absolute left-[4%] top-[6%] w-[40%] rotate-[-9deg] overflow-hidden border border-paper/20 bg-charcoal p-2 shadow-2xl"><img src={img.property} alt="Foto de imóvel" className="aspect-[4/3] w-full object-cover grayscale" /><p className="p-2 font-mono text-[9px] uppercase tracking-[.14em] text-paper/55">IMG_8391</p></div><div className="absolute left-[23%] top-[24%] w-[39%] rotate-[5deg] overflow-hidden border border-paper/20 bg-charcoal p-2 shadow-2xl"><img src={img.catalogDesktop} alt="Catálogo Vello" className="aspect-[4/3] w-full object-cover grayscale" /><p className="p-2 font-mono text-[9px] uppercase tracking-[.14em] text-paper/55">qual era o valor?</p></div><div className="absolute right-[4%] top-[4%] w-[49%] rotate-[2deg] overflow-hidden border border-paper/20 bg-paper p-2 text-ink shadow-2xl"><img src={img.catalog} alt="Catálogo público organizado" className="aspect-[9/11] w-full object-cover object-top" /><div className="px-3 py-4"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-stone">Um link</p><p className="mt-1 font-display text-[24px] tracking-[-.05em]">vello.com/nome</p></div></div></Reveal></div></Container></section>; }

function CatalogShowcase() { return <section className="bg-paper py-24 md:py-40"><Container><div className="grid gap-12 lg:grid-cols-[.34fr_.66fr] lg:items-center"><Reveal className="lg:pr-4"><Eyebrow>Seu catálogo</Eyebrow><h2 className="mt-5 font-display text-[clamp(46px,5.2vw,76px)] font-medium leading-[.92] tracking-[-.075em]">Um link.<br />Todo o seu portfólio.</h2><p className="mt-7 max-w-[370px] font-body text-[16px] leading-relaxed text-ash">Seu perfil, seus imóveis, filtros e contato em uma experiência feita para abrir no celular.</p><div className="mt-9 space-y-3 border-t border-line pt-5 font-body text-sm"><p>Seu perfil</p><p>Seus imóveis</p><p>Seu contato</p></div></Reveal><Reveal delay={.1}><div className="overflow-hidden border border-line bg-cream p-2 shadow-[0_32px_80px_-45px_rgba(11,11,10,.35)] sm:p-4"><img src={img.catalogDesktop} width="1425" height="891" alt="Catálogo público real da Vello com imóveis e filtros" className="block w-full" /></div></Reveal></div></Container></section>; }

function SelectionsShowcase() { return <section className="overflow-hidden bg-cream py-24 md:py-36"><Container><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><Eyebrow>Seleções</Eyebrow><h2 className="mt-5 max-w-[550px] font-display text-[clamp(46px,5.2vw,76px)] font-medium leading-[.91] tracking-[-.075em]">Nem todo cliente<br />precisa ver tudo.</h2><p className="mt-7 max-w-[465px] font-body text-[16px] leading-relaxed text-ash">Escolha os imóveis certos, crie uma seleção e envie uma página feita para aquela conversa.</p></Reveal><Reveal delay={.1}><article className="border border-line bg-paper p-5 shadow-[0_25px_70px_-42px_rgba(11,11,10,.32)] sm:p-7"><div className="flex flex-wrap items-center justify-between gap-5 border-b border-line pb-5"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-stone">Seleção para</p><h3 className="mt-2 font-display text-[34px] font-medium tracking-[-.055em]">Marina</h3></div><div className="text-right font-mono text-[10px] uppercase tracking-[.13em] text-stone">Apartamento · 2+ quartos<br />Porto Alegre · até R$ 850 mil</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[img.property, img.catalogDesktop, img.dashboard].map((image, i) => <motion.div key={image} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .18 + i * .08 }} className="overflow-hidden border border-line bg-cream"><img src={image} alt="Imóvel selecionado" className="aspect-[4/3] w-full object-cover" /><p className="p-3 font-body text-[12px] font-medium">Imóvel selecionado</p></motion.div>)}</div><div className="mt-5 flex items-center justify-between bg-ink px-4 py-3 text-paper"><span className="font-body text-sm font-medium">Seleção para Marina</span><button onClick={() => track("selection_copy_link_click")} className="inline-flex items-center gap-2 font-body text-xs"><Copy size={14} /> Copiar link</button></div></article></Reveal></div></Container></section>; }

function HowItWorks() { const steps = [["01", "Crie seu perfil", "Configure suas informações e deixe a Vello com a sua cara."], ["02", "Adicione seus imóveis", "Fotos, valores e detalhes ficam organizados em um só lugar."], ["03", "Compartilhe", "Envie seu catálogo ou uma seleção diretamente para o cliente."]]; return <section id="como-funciona" className="bg-paper py-24 md:py-36"><Container><Eyebrow>Sem complicação</Eyebrow><h2 className="mt-5 max-w-[720px] font-display text-[clamp(46px,5.2vw,76px)] font-medium leading-[.92] tracking-[-.075em]">Da primeira foto<br />ao link enviado.</h2><div className="mt-16 grid border-t border-line md:grid-cols-3">{steps.map(([number, title, text], i) => <Reveal key={number} delay={i * .08} className={`border-b border-line py-8 md:min-h-[285px] md:py-10 ${i ? "md:border-l md:pl-9" : "md:pr-9"}`}><p className="font-display text-[55px] font-medium leading-none tracking-[-.07em] text-mist">{number}</p><h3 className="mt-9 font-display text-[28px] font-medium tracking-[-.045em]">{title}</h3><p className="mt-4 max-w-[280px] font-body text-[15px] leading-relaxed text-ash">{text}</p></Reveal>)}</div></Container></section>; }

function Pricing() { return <section id="planos" className="bg-cream py-24 md:py-36"><Container><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><Reveal><Eyebrow>Planos</Eyebrow><h2 className="mt-5 max-w-[500px] font-display text-[clamp(46px,5.2vw,76px)] font-medium leading-[.92] tracking-[-.075em]">Comece simples.<br />Apresente melhor.</h2></Reveal><Reveal delay={.1}><div className="border border-ink bg-ink p-7 text-paper sm:p-10"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-paper/45">Vello</p><h3 className="mt-10 max-w-[430px] font-display text-[38px] font-medium leading-[.96] tracking-[-.055em]">Um catálogo profissional, feito a partir do seu trabalho.</h3><p className="mt-6 max-w-[490px] font-body text-[15px] leading-relaxed text-paper/65">Os detalhes comerciais da Vello serão publicados junto com o lançamento. Enquanto isso, você já pode criar sua conta e conhecer a estrutura do produto.</p><a href={signup} onClick={() => track("pricing_cta_click")} className="mt-9 inline-flex items-center gap-3 rounded-full bg-paper px-6 py-4 font-body text-sm font-semibold text-ink">Criar meu catálogo <ArrowRight size={16} /></a></div></Reveal></div></Container></section>; }

const questions = [["Preciso ter um site para usar a Vello?", "Não. A Vello publica um catálogo próprio com seu perfil, imóveis e formas de contato."], ["O cliente precisa criar uma conta?", "Não. O cliente abre o link do seu catálogo ou da seleção diretamente no navegador."], ["Posso atualizar meus imóveis depois?", "Sim. Você pode editar informações, fotos e disponibilidade pelo painel."], ["Posso criar uma seleção para cada cliente?", "Sim. As seleções permitem reunir imóveis específicos e compartilhar uma página própria para cada conversa."], ["A Vello funciona bem no celular?", "Sim. O catálogo público foi desenhado para ser aberto e navegado pelo celular."], ["Como o cliente entra em contato comigo?", "O catálogo inclui seu contato para que o interessado possa iniciar a conversa com você."]];
function Faq() { const [open, setOpen] = useState<number | null>(0); return <section className="bg-paper py-24 md:py-36"><Container><div className="grid gap-14 lg:grid-cols-[.78fr_1.22fr]"><div><Eyebrow>Perguntas frequentes</Eyebrow><h2 className="mt-5 max-w-[420px] font-display text-[clamp(46px,5vw,72px)] font-medium leading-[.92] tracking-[-.075em]">Antes de criar<br />sua Vello.</h2></div><div className="border-t border-line">{questions.map(([question, answer], i) => <div key={question} className="border-b border-line"><button onClick={() => { setOpen(open === i ? null : i); track("faq_open", { question }); }} aria-expanded={open === i} className="flex min-h-[76px] w-full items-center justify-between gap-5 py-5 text-left font-display text-[21px] font-medium tracking-[-.035em]"><span>{question}</span><ChevronDown className={`shrink-0 transition-transform ${open === i ? "rotate-180" : ""}`} size={20} /></button><AnimatePresence initial={false}>{open === i && <motion.p initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden pb-6 pr-8 font-body text-[15px] leading-relaxed text-ash">{answer}</motion.p>}</AnimatePresence></div>)}</div></div></Container></section>; }

function FinalCta() { return <section id="final-cta" className="overflow-hidden bg-ink py-24 text-paper md:py-36"><Container><div className="relative overflow-hidden border border-paper/15 px-6 py-16 sm:px-12 md:px-16 md:py-24"><div className="pointer-events-none absolute -right-28 -top-28 h-[420px] w-[420px] rounded-[48%] border border-paper/10" /><div className="pointer-events-none absolute -bottom-44 right-[15%] h-[430px] w-[520px] rounded-[50%] bg-paper/[.035]" /><Reveal className="relative max-w-[720px]"><Eyebrow>Sua Vello</Eyebrow><h2 className="mt-5 font-display text-[clamp(48px,6vw,82px)] font-medium leading-[.9] tracking-[-.077em] text-paper">Seu trabalho merece<br />uma apresentação à altura.</h2><p className="mt-7 max-w-[520px] font-body text-[16px] leading-relaxed text-paper/65">Troque fotos soltas por um catálogo pronto para abrir, navegar e compartilhar.</p><div className="mt-9 flex flex-wrap gap-3"><a href={signup} onClick={() => track("final_cta_click")} className="inline-flex items-center gap-3 rounded-full bg-paper px-6 py-4 font-body text-sm font-semibold text-ink">Criar minha Vello <ArrowUpRight size={16} /></a><a href={demo} className="rounded-full border border-paper/25 px-6 py-4 font-body text-sm font-medium text-paper">Ver demonstração</a></div></Reveal></div></Container></section>; }

function LandingFooter() { return <footer className="border-t border-paper/10 bg-ink py-12 text-paper"><Container><div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Logo variant="light" className="origin-left scale-[.88]" /><p className="mt-5 max-w-[230px] font-body text-sm leading-relaxed text-paper/55">Uma forma melhor de apresentar imóveis.</p></div><FooterColumn title="Produto" items={nav} /><FooterColumn title="Conta" items={[["Entrar", appPath("/login")], ["Criar catálogo", signup]]} /><FooterColumn title="Legal" items={[["Termos", "#"], ["Privacidade", "#"]]} /></div><p className="mt-16 border-t border-paper/10 pt-5 font-mono text-[10px] uppercase tracking-[.12em] text-paper/35">© {new Date().getFullYear()} Vello</p></Container></footer>; }
function FooterColumn({ title, items }: { title: string; items: string[][] }) { return <div><p className="font-mono text-[10px] uppercase tracking-[.15em] text-paper/40">{title}</p><div className="mt-5 flex flex-col gap-3">{items.map(([name, url]) => <a key={name} href={url} className="font-body text-sm text-paper/70 hover:text-paper">{name}</a>)}</div></div>; }
function MobileStickyCta() { const [visible, setVisible] = useState(false); useEffect(() => { const hero = document.getElementById("hero-primary-cta"), final = document.getElementById("final-cta"); if (!hero || !final) return; const observer = new IntersectionObserver(() => setVisible(hero.getBoundingClientRect().bottom < 0 && final.getBoundingClientRect().top > window.innerHeight), { threshold: 0 }); observer.observe(hero); observer.observe(final); return () => observer.disconnect(); }, []); return <AnimatePresence>{visible && <motion.div initial={{ y: 90 }} animate={{ y: 0 }} exit={{ y: 90 }} className="fixed inset-x-0 bottom-0 z-50 border-t border-line bg-paper/95 p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur md:hidden"><a href={signup} onClick={() => track("mobile_sticky_cta_click")} className="flex h-12 items-center justify-center rounded-full bg-ink font-body text-sm font-semibold text-paper">Criar meu catálogo</a></motion.div>}</AnimatePresence>; }

