import { Building2, Heart, Home, MapPin, Plus, Search, Share2 } from "lucide-react";
import { appPath } from "../lib/paths";

type Screen = "customize" | "dashboard" | "catalog" | "selection" | "property" | "share";

export function VelloProductPreview({ screen, compact = false }: { screen: Screen; compact?: boolean }) {
  return <div className={`h-full w-full overflow-hidden bg-[#faf9f6] text-[#0b0b0a] ${compact ? "text-[.52em]" : "text-[.72em]"}`}>
    {screen === "customize" && <Customize />}
    {screen === "dashboard" && <Dashboard />}
    {screen === "catalog" && <Catalog />}
    {screen === "selection" && <Selection />}
    {screen === "property" && <Property />}
    {screen === "share" && <Share />}
  </div>;
}

const Top = () => <div className="flex h-[12%] items-center justify-between border-b border-[#dedbd3] px-[7%]"><span className="font-semibold">Vello</span><Share2 size="1.1em" /></div>;
const Profile = () => <div className="mx-[6%] mt-[5%] flex items-center gap-[.7em] rounded-[1.2em] bg-white p-[.8em] shadow-[0_.6em_1.4em_rgba(11,11,10,.08)]"><span className="grid h-[2.4em] w-[2.4em] place-items-center rounded-full bg-[#0b0b0a] text-white">J</span><span><b className="block">Jose</b><small className="block text-[#8b8880]">Corretor de imóveis · CRECI 22222222-F</small></span></div>;
const Nav = () => <div className="absolute inset-x-0 bottom-0 flex h-[9%] items-center justify-around border-t border-[#dedbd3] bg-white text-[#8b8880]"><Home size="1.1em"/><Building2 size="1.1em"/><span className="grid h-[2.5em] w-[2.5em] place-items-center rounded-full bg-[#0b0b0a] text-white"><Plus size="1.2em"/></span><Heart size="1.1em"/></div>;
function Customize() { return <div className="relative h-full"><Top/><div className="px-[7%] pt-[8%]"><small className="uppercase tracking-[.15em] text-[#8b8880]">Seu catálogo</small><h3 className="mt-[.3em] text-[1.8em] font-semibold leading-none">Personalize sua Vello</h3><p className="mt-[.7em] text-[.72em] leading-relaxed text-[#5c5a54]">Ajuste a identidade que seus clientes vão ver.</p><div className="mt-[1.5em] rounded-[1em] border border-[#dedbd3] bg-white p-[1em]"><b className="block text-[.9em]">Perfil público</b><div className="mt-[.8em] flex items-center gap-[.7em]"><span className="grid h-[3em] w-[3em] place-items-center rounded-full bg-[#0b0b0a] text-white">J</span><span><b className="block text-[.82em]">Jose</b><small className="text-[#8b8880]">Corretor de imóveis</small></span></div></div><div className="mt-[.8em] rounded-[1em] border border-[#dedbd3] bg-white p-[1em]"><b className="block text-[.9em]">Aparência</b><small className="mt-[.35em] block text-[#8b8880]">Cor principal do catálogo</small><div className="mt-[.9em] flex gap-[.7em]"><span className="h-[2.3em] w-[2.3em] rounded-full border-[.25em] border-white bg-[#0b0b0a] ring-1 ring-[#0b0b0a]"/><span className="h-[2.3em] w-[2.3em] rounded-full bg-[#d8d0c3]"/><span className="h-[2.3em] w-[2.3em] rounded-full bg-[#6f7866]"/><span className="h-[2.3em] w-[2.3em] rounded-full bg-[#5e687b]"/></div></div><div className="mt-[.8em] rounded-[1em] border border-[#dedbd3] bg-white p-[1em]"><b className="block text-[.9em]">Informações de contato</b><small className="mt-[.35em] block text-[#8b8880]">WhatsApp e localização visíveis</small></div><div className="mt-[1em] rounded-full bg-[#0b0b0a] py-[.9em] text-center text-[.78em] font-semibold text-white">Salvar alterações</div></div></div> }
function Dashboard() { return <div className="relative h-full"><Top/><div className="px-[7%] pt-[7%]"><small className="text-[#8b8880]">Boa tarde, Jose.</small><h3 className="mt-[.2em] text-[1.65em] font-semibold leading-[.95]">Seus imóveis estão todos por aqui.</h3><div className="mt-[1em] flex gap-[.5em]"><button className="rounded-full border border-[#dedbd3] px-[.75em] py-[.5em] text-[.68em]">Personalizar catálogo</button><button className="rounded-full bg-[#0b0b0a] px-[.8em] py-[.5em] text-[.68em] text-white">+ Novo imóvel</button></div><div className="mt-[1.2em] grid grid-cols-2 gap-[.6em]">{["Disponíveis", "Reservados", "Vendidos / alugados", "Total"].map(x=><div key={x} className="rounded-[.9em] border border-[#dedbd3] bg-white p-[.8em]"><small className="uppercase text-[#8b8880]">{x}</small><b className="mt-[.5em] block text-[1.8em]">0</b></div>)}</div><h4 className="mt-[1.5em] text-[1.2em]">Seus imóveis</h4><p className="mt-[.25em] text-[.7em] text-[#5c5a54]">Seu catálogo ainda está vazio.</p></div><Nav/></div> }
function Catalog() { return <div className="relative h-full"><Top/><Profile/><div className="px-[6%] pt-[6%]"><h3 className="text-[1.8em] font-semibold">Todos os imóveis</h3><p className="mt-[.4em] text-[.75em] text-[#5c5a54]">Explore todas as opções disponíveis.</p><div className="mt-[1.3em] border-y border-[#dedbd3] py-[.8em]"><span className="flex items-center gap-[.5em] rounded-full border border-[#dedbd3] bg-white px-[.8em] py-[.65em] text-[.7em] text-[#8b8880]"><Search size="1em"/> Onde você quer morar?</span><div className="mt-[.7em] flex gap-[.4em] text-[.65em]"><b className="rounded-full bg-[#0b0b0a] px-[.9em] py-[.55em] text-white">Todos</b><span className="rounded-full border border-[#dedbd3] px-[.8em] py-[.55em]">Comprar</span><span className="rounded-full border border-[#dedbd3] px-[.8em] py-[.55em]">Alugar</span></div></div><small className="mt-[2em] block uppercase tracking-[.15em] text-[#8b8880]">Sem resultados</small><h4 className="mt-[.6em] text-[1.45em] leading-none">Novas oportunidades em breve.</h4><p className="mt-[.8em] text-[.7em] leading-relaxed text-[#5c5a54]">No momento não há imóveis que combinem com essa busca.</p></div></div> }
function Selection() { const homes = [["Casa contemporânea", "R$ 1,89 mi", "/landing/property-photo-1.png"], ["Apartamento com vista", "R$ 840 mil", "/landing/property-photo-2.png"], ["Cobertura pronta", "R$ 2,35 mi", "/landing/property-photo-3.png"]]; return <div className="relative h-full"><Top/><div className="px-[7%] pt-[8%]"><small className="uppercase tracking-[.15em] text-[#8b8880]">Seleção para</small><h3 className="mt-[.3em] text-[1.8em] font-semibold">Marina</h3><p className="mt-[.5em] text-[.72em] text-[#5c5a54]">3 imóveis selecionados para essa conversa.</p><div className="mt-[1.5em] space-y-[.7em]">{homes.map(([name, price, photo])=><div key={name} className="flex gap-[.7em] rounded-[.9em] border border-[#dedbd3] bg-white p-[.6em]"><img src={appPath(photo)} alt="" className="h-[3.8em] w-[4em] rounded-[.5em] object-cover"/><span><b className="block text-[.85em]">{name}</b><small className="text-[#8b8880]">Porto Alegre · {price}</small></span></div>)}</div></div><Nav/></div> }
function Property() { return <div className="relative h-full"><Top/><img src={appPath("/landing/property-photo-1.png")} alt="Casa contemporânea" className="mx-[6%] mt-[7%] h-[29%] w-[88%] rounded-[1.2em] object-cover"/><div className="px-[7%] pt-[6%]"><small className="uppercase text-[#8b8880]">À venda</small><h3 className="mt-[.5em] text-[1.55em] leading-none">Casa contemporânea no Moinhos</h3><b className="mt-[.9em] block text-[1.25em]">R$ 1.890.000</b><p className="mt-[1em] flex items-center gap-[.3em] text-[.72em] text-[#5c5a54]"><MapPin size="1em"/> Moinhos de Vento · Porto Alegre</p><div className="mt-[1.5em] border-y border-[#dedbd3] py-[.8em] text-[.75em]">3 quartos · 2 vagas · 184m²</div></div></div> }
function Share() { return <div className="relative h-full"><Top/><div className="px-[7%] pt-[10%]"><span className="grid h-[3.5em] w-[3.5em] place-items-center rounded-full bg-[#0b0b0a] text-white"><Share2 size="1.5em"/></span><h3 className="mt-[1em] text-[1.7em] leading-none">Pronto para compartilhar.</h3><p className="mt-[.9em] text-[.75em] leading-relaxed text-[#5c5a54]">Seu catálogo já tem um link próprio para enviar aos clientes.</p><div className="mt-[1.5em] rounded-[.8em] border border-[#dedbd3] bg-white p-[.8em] text-[.75em]">vello.com/jose</div><button className="mt-[.8em] w-full rounded-full bg-[#0b0b0a] py-[.9em] text-[.78em] font-semibold text-white">Copiar link</button></div></div> }
