import { ArrowRight, Check, LayoutDashboard, MapPin, Palette, Plus, Send, Share2 } from "lucide-react";
import { appPath } from "../lib/paths";
import { Logo } from "./Logo";
import { Container, Eyebrow, Reveal } from "./Primitives";

const signup = appPath("/cadastro");
const login = appPath("/login");
const propertyImages = ["/landing/property-photo-1.png", "/landing/property-photo-2.png", "/landing/property-photo-3.png"];

export function VelloLandingMinimal() {
  return <div className="min-h-screen overflow-hidden bg-paper text-ink">
    <Header />
    <main>
      <Hero />
      <OnboardingFlow />
      <CatalogSection />
      <Closing />
    </main>
    <Footer />
  </div>;
}

function Header() {
  return <header className="border-b border-line bg-paper"><Container className="flex h-[76px] items-center justify-between"><a href="#inicio" aria-label="Vello — início"><Logo className="origin-left scale-[.86]" /></a><nav className="hidden items-center gap-8 font-body text-[14px] text-ash md:flex"><a href="#como-funciona" className="hover:text-ink">Como funciona</a><a href="#catalogo" className="hover:text-ink">Catálogo</a></nav><div className="flex items-center gap-3"><a href={login} className="hidden px-3 py-2 font-body text-[14px] text-ash hover:text-ink sm:inline">Entrar</a><a href={signup} className="rounded-[10px] bg-ink px-4 py-3 font-body text-[13px] font-semibold text-paper transition hover:bg-charcoal">Criar catálogo</a></div></Container></header>;
}

function Hero() {
  return <section id="inicio" className="border-b border-line bg-paper"><Container className="grid gap-14 py-16 md:py-24 lg:grid-cols-[.87fr_1.13fr] lg:items-center lg:gap-12 lg:py-28"><Reveal y={14}><Eyebrow>Vello para corretores</Eyebrow><h1 className="mt-5 max-w-[620px] font-display text-[clamp(48px,6vw,82px)] font-semibold leading-[.9] tracking-[-.07em]">Seus imóveis,<br />no lugar certo.</h1><p className="mt-7 max-w-[500px] font-body text-[17px] leading-relaxed text-ash">Organize seu portfólio, crie um catálogo com a sua identidade e envie uma experiência profissional para cada cliente.</p><div className="mt-9 flex flex-wrap gap-3"><a href={signup} className="inline-flex h-12 items-center gap-2 rounded-[10px] bg-ink px-5 font-body text-[14px] font-semibold text-paper transition hover:bg-charcoal">Começar agora <ArrowRight size={16} /></a><a href="#como-funciona" className="inline-flex h-12 items-center rounded-[10px] border border-line bg-white px-5 font-body text-[14px] font-medium transition hover:border-ink">Conhecer a Vello</a></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[.12em] text-stone">Seu catálogo pronto para compartilhar.</p></Reveal><Reveal delay={.1} y={18}><DashboardPreview /></Reveal></Container></section>;
}

function DashboardPreview() {
  return <div className="overflow-hidden rounded-[24px] border border-line bg-white shadow-[0_28px_80px_-46px_rgba(11,11,10,.38)]"><div className="flex h-12 items-center justify-between border-b border-line px-5"><span className="font-display text-[15px] font-semibold">Vello</span><span className="h-2 w-2 rounded-full bg-ink" /></div><div className="grid min-h-[430px] grid-cols-[76px_1fr] sm:grid-cols-[150px_1fr]"><aside className="border-r border-line bg-[#f7f6f2] px-3 py-5 sm:px-4"><div className="space-y-2">{[[LayoutDashboard, "Início"], [MapPin, "Imóveis"], [Send, "Seleções"], [Palette, "Personalizar"]].map(([Icon, label], index) => <div key={label as string} className={`flex h-9 items-center gap-2 rounded-[8px] px-2 font-body text-[12px] ${index === 0 ? "bg-ink text-paper" : "text-ash"}`}><Icon size={14} /><span className="hidden sm:inline">{label as string}</span></div>)}</div></aside><div className="min-w-0 p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-body text-[12px] text-ash">Boa tarde, Jose.</p><h2 className="mt-1 font-display text-[25px] font-semibold tracking-[-.05em] sm:text-[31px]">Seus imóveis estão<br />todos por aqui.</h2></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[10px] bg-ink text-paper"><Plus size={18} /></span></div><div className="mt-6 grid grid-cols-2 gap-3"><Stat label="Disponíveis" value="08" /><Stat label="Reservados" value="02" /><Stat label="Vendidos" value="12" /><Stat label="Total" value="22" /></div><div className="mt-7 flex items-center justify-between"><div><h3 className="font-display text-[18px] font-semibold tracking-[-.03em]">Seus imóveis</h3><p className="mt-1 font-body text-[11px] text-ash">Os mais recentes do seu catálogo.</p></div><span className="font-body text-[12px] underline underline-offset-4">Ver todos</span></div><div className="mt-4 grid grid-cols-2 gap-3"><MiniProperty image={propertyImages[0]} title="Casa no Moinhos" /><MiniProperty image={propertyImages[1]} title="Apartamento com vista" /></div></div></div></div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-[12px] border border-line bg-paper p-3"><p className="font-mono text-[8px] uppercase tracking-[.1em] text-stone">{label}</p><p className="mt-2 font-display text-[24px] font-semibold tracking-[-.05em]">{value}</p></div>; }
function MiniProperty({ image, title }: { image: string; title: string }) { return <article className="overflow-hidden rounded-[10px] border border-line bg-white"><img src={appPath(image)} alt="" className="aspect-[1.45/1] w-full object-cover" /><p className="truncate px-2 py-2 font-body text-[10px] font-medium">{title}</p></article>; }

function OnboardingFlow() {
  const steps = [["01", "Crie seu perfil", "Suas informações profissionais e seu link público."], ["02", "Adicione seus imóveis", "Fotos, detalhes e valores organizados com clareza."], ["03", "Compartilhe", "Um catálogo pronto para abrir em qualquer tela."]];
  return <section id="como-funciona" className="bg-cream py-24 md:py-32"><Container><Reveal><Eyebrow>Comece em poucos passos</Eyebrow><div className="mt-5 grid gap-6 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><h2 className="max-w-[610px] font-display text-[clamp(42px,5vw,68px)] font-semibold leading-[.91] tracking-[-.065em]">Uma rotina simples para apresentar melhor.</h2><p className="max-w-[430px] font-body text-[16px] leading-relaxed text-ash">A Vello acompanha o seu trabalho desde o primeiro imóvel até o momento de compartilhar com o cliente.</p></div></Reveal><div className="mt-14 grid border-y border-line md:grid-cols-3">{steps.map(([number, title, text], index) => <Reveal key={number} delay={index * .08} className={`py-8 md:min-h-[230px] md:py-10 ${index ? "border-t border-line md:border-l md:border-t-0 md:pl-9" : "md:pr-9"}`}><p className="font-mono text-[11px] uppercase tracking-[.14em] text-stone">{number}</p><h3 className="mt-10 font-display text-[27px] font-semibold tracking-[-.045em]">{title}</h3><p className="mt-3 max-w-[290px] font-body text-[15px] leading-relaxed text-ash">{text}</p></Reveal>)}</div></Container></section>;
}

function CatalogSection() {
  return <section id="catalogo" className="bg-paper py-24 md:py-32"><Container className="grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><Reveal><Eyebrow>O seu espaço público</Eyebrow><h2 className="mt-5 max-w-[500px] font-display text-[clamp(43px,5vw,68px)] font-semibold leading-[.91] tracking-[-.065em]">Um catálogo que parece seu.</h2><p className="mt-6 max-w-[430px] font-body text-[16px] leading-relaxed text-ash">Escolha a aparência, organize os imóveis e compartilhe uma página que deixa seu trabalho fácil de entender.</p><ul className="mt-8 space-y-3 border-t border-line pt-5 font-body text-[14px] text-ash"><li className="flex gap-3"><Check size={17} className="shrink-0 text-ink" />Perfil profissional e contato sempre visíveis.</li><li className="flex gap-3"><Check size={17} className="shrink-0 text-ink" />Filtros para o cliente encontrar o que procura.</li><li className="flex gap-3"><Check size={17} className="shrink-0 text-ink" />Seleções prontas para cada conversa.</li></ul></Reveal><Reveal delay={.12}><CatalogPreview /></Reveal></Container></section>;
}

function CatalogPreview() {
  return <div className="overflow-hidden rounded-[24px] border border-line bg-[#f5f2ec] shadow-[0_28px_80px_-48px_rgba(11,11,10,.36)]"><div className="flex h-14 items-center justify-between border-b border-black/10 bg-ink px-5 text-paper"><span className="font-display text-[15px] font-semibold">Vello</span><span className="hidden font-body text-[11px] text-paper/65 sm:inline">Catálogo &nbsp;&nbsp; Imóveis &nbsp;&nbsp; Seleções</span><Share2 size={16} /></div><div className="p-5 sm:p-7"><div className="flex items-center gap-3 rounded-[14px] bg-white p-3 shadow-[0_12px_28px_rgba(11,11,10,.06)]"><span className="grid h-9 w-9 place-items-center rounded-full bg-ink font-display text-xs text-paper">J</span><span><b className="block font-body text-[12px]">Jose</b><small className="block font-body text-[10px] text-ash">Catálogo digital para imóveis</small></span></div><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[9px] uppercase tracking-[.14em] text-stone">Catálogo de imóveis</p><h3 className="mt-2 font-display text-[30px] font-semibold tracking-[-.055em] sm:text-[37px]">Todos os imóveis</h3></div><button className="rounded-full border border-line bg-white px-4 py-2 font-body text-[11px] text-ash">Onde você quer morar?</button></div><div className="mt-5 flex gap-2 overflow-hidden">{["Todos", "Comprar", "Alugar", "Casas"].map((filter, index) => <span key={filter} className={`shrink-0 rounded-full px-3 py-2 font-body text-[10px] ${index === 0 ? "bg-ink text-paper" : "border border-line bg-white text-ash"}`}>{filter}</span>)}</div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{propertyImages.map((image, index) => <article key={image} className="overflow-hidden rounded-[12px] bg-white"><img src={appPath(image)} alt="Imóvel no catálogo" className="aspect-[1.2/1] w-full object-cover" /><div className="p-3"><p className="font-display text-[14px] font-semibold leading-tight">{["Casa contemporânea", "Apartamento alto", "Cobertura pronta"][index]}</p><p className="mt-2 font-body text-[10px] text-ash">Porto Alegre · RS</p></div></article>)}</div></div></div>;
}

function Closing() { return <section className="bg-ink py-24 text-paper md:py-32"><Container><Reveal className="max-w-[760px]"><Eyebrow>Sua Vello</Eyebrow><h2 className="mt-5 font-display text-[clamp(48px,6vw,78px)] font-semibold leading-[.9] tracking-[-.07em]">Seu trabalho merece<br />ser bem apresentado.</h2><p className="mt-7 max-w-[520px] font-body text-[16px] leading-relaxed text-paper/65">Crie uma conta, organize seu portfólio e tenha um catálogo pronto para enviar.</p><a href={signup} className="mt-9 inline-flex h-12 items-center gap-2 rounded-[10px] bg-paper px-5 font-body text-[14px] font-semibold text-ink transition hover:bg-white">Criar meu catálogo <ArrowRight size={16} /></a></Reveal></Container></section>; }

function Footer() { return <footer className="border-t border-paper/10 bg-ink pb-9 text-paper"><Container className="flex flex-col justify-between gap-6 border-t border-paper/10 pt-9 sm:flex-row sm:items-center"><Logo variant="light" className="origin-left scale-[.82]" /><p className="font-mono text-[10px] uppercase tracking-[.12em] text-paper/40">© {new Date().getFullYear()} Vello</p></Container></footer>; }
