alter table public.profiles add column if not exists bio text not null default '', add column if not exists show_instagram boolean not null default true, add column if not exists show_creci boolean not null default true, add column if not exists show_completed_properties boolean not null default false;
alter table public.properties add column if not exists publication_status text not null default 'published' check (publication_status in ('draft','published')), add column if not exists slug text, add constraint properties_user_slug_unique unique (user_id, slug);

create table if not exists public.selections (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_name text not null, client_whatsapp text, slug text not null, intro_message text not null default 'Separei algumas opções que combinam com o que você procura.', status text not null default 'active' check (status in ('active','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, slug));
create table if not exists public.selection_properties (id uuid primary key default gen_random_uuid(), selection_id uuid not null references public.selections(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, position smallint not null default 0 check (position >= 0), unique(selection_id, property_id), unique(selection_id, position));

create index if not exists properties_owner_created_idx on public.properties(user_id, created_at desc);
create index if not exists selections_owner_created_idx on public.selections(user_id, created_at desc);
create index if not exists selection_properties_selection_idx on public.selection_properties(selection_id, position);
alter table public.selections enable row level security;
alter table public.selection_properties enable row level security;
create policy "selections_owner_all" on public.selections for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "selection_properties_owner_all" on public.selection_properties for all to authenticated using (exists (select 1 from public.selections s where s.id = selection_id and s.user_id = (select auth.uid()))) with check (exists (select 1 from public.selections s where s.id = selection_id and s.user_id = (select auth.uid())));
create trigger selections_set_updated_at before update on public.selections for each row execute function public.set_updated_at();

create or replace function public.get_catalog(catalog_slug text) returns jsonb language sql security definer set search_path = '' stable as $$
  select jsonb_build_object('profile', jsonb_build_object('professional_name', p.professional_name, 'avatar_url', p.avatar_url, 'creci', case when p.show_creci then p.creci else null end, 'city', p.city, 'state', p.state, 'instagram', case when p.show_instagram then p.instagram else null end, 'slug', p.slug, 'bio', p.bio), 'properties', coalesce((select jsonb_agg(jsonb_build_object('id', pr.id, 'slug', pr.slug, 'title', pr.title, 'description', pr.description, 'transaction_type', pr.transaction_type, 'property_type', pr.property_type, 'price', pr.price, 'city', pr.city, 'neighborhood', pr.neighborhood, 'bedrooms', pr.bedrooms, 'bathrooms', pr.bathrooms, 'parking_spaces', pr.parking_spaces, 'area', pr.area, 'features', pr.features, 'images', coalesce((select jsonb_agg(jsonb_build_object('image_url', pi.image_url, 'position', pi.position) order by pi.position) from public.property_images pi where pi.property_id = pr.id), '[]'::jsonb)) order by pr.created_at desc) from public.properties pr where pr.user_id = p.user_id and pr.publication_status = 'published' and (pr.status = 'available' or p.show_completed_properties)), '[]'::jsonb)) from public.profiles p where p.slug = lower(catalog_slug) limit 1;
$$;

create or replace function public.get_selection(selection_slug text) returns jsonb language sql security definer set search_path = '' stable as $$
  select jsonb_build_object('client_name', s.client_name, 'intro_message', s.intro_message, 'slug', s.slug, 'profile', jsonb_build_object('professional_name', p.professional_name, 'whatsapp', p.whatsapp, 'avatar_url', p.avatar_url), 'properties', coalesce((select jsonb_agg(jsonb_build_object('id', pr.id, 'title', pr.title, 'price', pr.price, 'city', pr.city, 'neighborhood', pr.neighborhood, 'bedrooms', pr.bedrooms, 'bathrooms', pr.bathrooms, 'parking_spaces', pr.parking_spaces, 'area', pr.area, 'images', coalesce((select jsonb_agg(jsonb_build_object('image_url', pi.image_url, 'position', pi.position) order by pi.position) from public.property_images pi where pi.property_id = pr.id), '[]'::jsonb)) order by sp.position) from public.selection_properties sp join public.properties pr on pr.id = sp.property_id where sp.selection_id = s.id and pr.publication_status = 'published'), '[]'::jsonb)) from public.selections s join public.profiles p on p.user_id = s.user_id where s.slug = lower(selection_slug) and s.status = 'active' limit 1;
$$;
revoke all on function public.get_catalog(text) from public;
grant execute on function public.get_catalog(text) to anon, authenticated;
revoke all on function public.get_selection(text) from public;
grant execute on function public.get_selection(text) to anon, authenticated;
