import { AlertCircle, ArrowLeft, CheckCircle2, LoaderCircle, Mail, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import type { FormEvent } from 'react';
import { AuthLayout } from './AuthLayout';
import { AuthInput } from './AuthInput';
import { PasswordInput } from './PasswordInput';
import { login, resendSignupEmail, sendPasswordReset, updatePassword } from '../../lib/auth';
import { appPath } from '../../lib/paths';

type AuthMode = 'login' | 'signup' | 'forgot' | 'reset' | 'verify';

export function AuthPage({ mode, invited = false }: { mode: AuthMode; invited?: boolean }) {
  if (mode === 'login') return <Login />;
  if (mode === 'signup') return <Signup />;
  if (mode === 'forgot') return <ForgotPassword />;
  if (mode === 'reset') return <ResetPassword invited={invited} />;
  return <VerifyEmail />;
}

function Shell({ children }: { children: React.ReactNode }) {
  return <AuthLayout><div className="w-full">{children}</div></AuthLayout>;
}

function Header({ title, description }: { title: string; description: string }) { return <div className="mb-8"><h1 className="font-display text-[36px] font-semibold leading-[1.02] tracking-[-0.035em] text-ink">{title}</h1><p className="mt-4 font-body text-[15px] leading-relaxed text-ash">{description}</p></div>; }
function ErrorMessage({ text }: { text: string }) { return <div role="alert" className="mb-5 flex items-start gap-2.5 rounded-[12px] border border-red-200 bg-red-50 px-3.5 py-3 text-[13px] text-red-700 shadow-[0_10px_30px_-26px_rgba(185,28,28,.45)]"><AlertCircle size={16} className="mt-0.5 shrink-0" />{text}</div>; }
function LoadingButton({ loading, children }: { loading: boolean; children: React.ReactNode }) { return <button disabled={loading} aria-busy={loading} className="vello-primary bg-sky text-ink vello-action flex h-12 w-full items-center justify-center gap-2 rounded-full font-body text-[14px] font-semibold disabled:cursor-wait disabled:opacity-70">{loading && <LoaderCircle size={16} className="animate-spin" />}{loading ? 'Aguarde...' : children}</button>; }

function Login() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!email.includes('@') || password.length < 8) { setError('E-mail ou senha incorretos.'); return; } setLoading(true); try { await login(email, password); window.location.href = appPath('/onboarding'); } catch { setError('E-mail ou senha incorretos.'); setLoading(false); } };
  return <Shell><Header title="Bem-vindo de volta." description="Entre para cuidar da sua agenda e dos seus serviços." />{error && <ErrorMessage text={error} />}<form onSubmit={submit} className="space-y-4"><AuthInput label="E-mail" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="seu@email.com" autoComplete="email" required /><div><PasswordInput label="Senha" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="••••••••" autoComplete="current-password" required /><div className="mt-2 text-right"><a href={appPath('/esqueci-senha')} className="font-body text-[12px] text-ash underline-offset-4 hover:text-ink hover:underline">Esqueci minha senha</a></div></div><LoadingButton loading={loading}>Entrar</LoadingButton></form><p className="mt-7 text-center font-body text-[13px] text-ash">Ainda não participa? <a href={appPath('/cadastro')} className="font-medium text-ink underline underline-offset-4">Saiba sobre o beta</a></p></Shell>;
}

function Signup() {
  return <Shell><SuccessIcon icon={<ShieldCheck size={22} />} /><Header title="Beta fechado por convite." description="Estamos acompanhando de perto as primeiras profissionais para melhorar a Vello antes da abertura pública." /><div className="rounded-[14px] border border-line bg-paper p-4 font-body text-[13px] leading-relaxed text-ash">Se você recebeu um convite, abra o link enviado pela equipe Vello. Ele confirma seu e-mail e permite que você escolha sua própria senha.</div><a href={appPath('/login')} className="vello-primary bg-sky text-ink mt-5 flex h-12 w-full items-center justify-center rounded-full font-body text-[14px] font-semibold">Já tenho acesso</a></Shell>;
}

function ForgotPassword() { const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [email, setEmail] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setLoading(true); try { await sendPasswordReset(email); setSent(true); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível enviar o link.'); } finally { setLoading(false); } }; if (sent) return <Shell><SuccessIcon icon={<Mail size={22} />} /><Header title="Confira seu e-mail." description={`Enviamos um link de recuperação para ${email}.`} /><a href={appPath('/login')} className="vello-primary bg-sky text-ink flex h-12 w-full items-center justify-center rounded-full font-body text-[14px] font-semibold">Voltar para o login</a></Shell>; return <Shell><a href={appPath('/login')} className="mb-8 inline-flex items-center gap-2 font-body text-[13px] text-ash hover:text-ink"><ArrowLeft size={15} /> Voltar para o login</a><Header title="Esqueceu sua senha?" description="Sem problema. Digite seu e-mail e enviaremos um link para criar uma nova senha." />{error && <ErrorMessage text={error} />}<form onSubmit={submit} className="space-y-4"><AuthInput label="E-mail" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="seu@email.com" autoComplete="email" required /><LoadingButton loading={loading}>Enviar link</LoadingButton></form></Shell>; }

function ResetPassword({ invited }: { invited: boolean }) { const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (password.length < 8 || !/[A-Za-z]/.test(password) || !/\d/.test(password)) { setError('A senha precisa ter no mínimo 8 caracteres, uma letra e um número.'); return; } if (password !== confirm) { setError('As senhas não coincidem.'); return; } setLoading(true); try { await updatePassword(password); setSaved(true); } catch { setError(invited ? 'Este convite expirou ou já foi usado. Peça um novo link à equipe Vello.' : 'O link expirou. Solicite uma nova recuperação.'); } finally { setLoading(false); } }; if (saved) return <Shell><SuccessIcon icon={<CheckCircle2 size={22} />} /><Header title={invited ? "Convite aceito." : "Senha alterada."} description={invited ? "Seu acesso à Vello está pronto. Agora vamos montar sua página e sua agenda." : "Sua senha foi atualizada com sucesso."} /><a href={appPath(invited ? '/onboarding' : '/login')} className="vello-primary bg-sky text-ink flex h-12 w-full items-center justify-center rounded-full font-body text-[14px] font-semibold">{invited ? 'Começar na Vello' : 'Entrar na Vello'}</a></Shell>; return <Shell><Header title={invited ? "Bem-vinda à Vello." : "Crie uma nova senha."} description={invited ? "Para aceitar o convite, escolha uma senha segura. Ela não será compartilhada com quem enviou o link." : "Escolha uma senha segura para continuar usando a Vello."} />{error && <ErrorMessage text={error} />}<form onSubmit={submit} className="space-y-4"><PasswordInput label="Nova senha" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="••••••••" autoComplete="new-password" required /><PasswordInput label="Confirmar nova senha" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="••••••••" autoComplete="new-password" required /><LoadingButton loading={loading}>{invited ? 'Aceitar convite' : 'Salvar nova senha'}</LoadingButton></form></Shell>; }

function VerifyEmail() { const [email, setEmail] = useState(() => sessionStorage.getItem('vello-verification-email') || ''); const [loading, setLoading] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const resend = async () => { if (!email) { setError('Digite o e-mail usado no cadastro.'); return; } setLoading(true); setError(''); try { await resendSignupEmail(email); setSent(true); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível reenviar o e-mail.'); } finally { setLoading(false); } }; return <Shell><SuccessIcon icon={<ShieldCheck size={22} />} /><Header title="Só falta confirmar seu e-mail." description="Enviamos um link para seu endereço de e-mail. Clique nele para ativar sua conta." />{error && <ErrorMessage text={error} />}<AuthInput label="E-mail do cadastro" type="email" value={email} onChange={(event) => { setEmail(event.target.value); setSent(false); }} placeholder="seu@email.com" autoComplete="email" required /><button type="button" onClick={resend} disabled={loading} className="vello-primary bg-sky text-ink mt-4 flex h-12 w-full items-center justify-center rounded-full font-body text-[14px] font-semibold disabled:opacity-60">{loading ? 'Enviando...' : sent ? 'E-mail reenviado' : 'Reenviar e-mail'}</button><a href={appPath('/login')} className="mt-4 flex h-12 w-full items-center justify-center rounded-full border border-line font-body text-[14px] font-medium text-ink">Voltar para o login</a></Shell>; }
function SuccessIcon({ icon }: { icon: React.ReactNode }) { return <div className="mb-6 flex h-12 w-12 items-center justify-center rounded-full bg-ink text-paper">{icon}</div>; }
